name: walletlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - eth-keys==0.4.0
    - eth-utils==2.3.1
    - eth-hash[pycryptodome]==0.6.0
    - pydantic==2.5.0
    - python-multipart==0.0.6

